[package]
name = "lfd_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
maxminddb = "0.17.0"
regex = "1.5.4"
serde = "1.0.130"
serde_json = "1.0.94"
clap = "3.0.0-beta.5"
flate2 = "1.0.21"
serde_derive = "1.0.130"